### ISSUE TITLE
Shader issues iOS

### ISSUE THREAD

**Issue by ddutchie** [keijiro/VJUI#2]
Knob is not filling when running on iOS : Unity 2017.3 and Metal Graphics API

Works great in editor. 

Any ideas?

**Comment by keijiro** [comment]
It works on my iPhoneX with Unity 2018.3b9. Could you test it with Unity 2018.3?

**Comment by FossFoss** [comment]
I'm also having trouble with the knob not filling on iOS (using iPhone XR) using various versions of Unity (2018.3.7f1, 2019.1.0f1). Like the OP, the knobs work fine in the game preview in the editor.

Do you have any demo projects with the knob functioning correctly on iOS?
