### ISSUE TITLE
More shader Issues on iOS

### ISSUE THREAD

**Issue by FossFoss** [keijiro/VJUI#3]
I added this as a comment on a closed issue, but maybe that wasn't a good idea. Sorry if I'm doubling up here.

I'm also having trouble with the knob not filling up. I've tried in Unity 2018.3.7f1 and 2.19.1.0f1. The MacOS and WebGL builds work fine, but not on my iPhone XR.

Do you have any demo projects with the knob working on iOS?

**Comment by keijiro** [comment]
Last time I tested it with my iPhone X, it worked correctly. So, it might be an unknown issue that only reproduces with iPhone XR (possibly including other recent iOS devices).

**Comment by FossFoss** [comment]
Perhaps! I'll try some builds on other iOS devices (old and new) and see how it turns out.

**Comment by keijiro** [comment]
This issue doesn't reproduce any more.
